// -----------------------------------------------------------------------------
// 1.3 – Design-time support for AddIndexOnProductName migration
// -----------------------------------------------------------------------------
// This file is auto-generated by EF Core and contains the snapshot of the model
// state after applying the AddIndexOnProductName migration.
// It now includes the index definition in the model snapshot.
// Do not edit manually – this file is regenerated when migrations are added.
// -----------------------------------------------------------------------------

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OracleDemo.Data;

#nullable disable

namespace OracleDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320160412_AddIndexOnProductName")]
    partial class AddIndexOnProductName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OracleDemo.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_DATE");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("PRICE");

                    b.Property<string>("ProductName")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("PRODUCT_NAME");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductName")
                        .HasDatabaseName("IX_PRODUCTS_NAME");

                    b.ToTable("PRODUCTS");
                });
#pragma warning restore 612, 618
        }
    }
}
