// -----------------------------------------------------------------------------
// 1.0 – Design-time support for InitialCreate migration
// -----------------------------------------------------------------------------
// This file is auto-generated by EF Core and contains the snapshot of the model
// state after applying the InitialCreate migration. It helps EF Core track
// changes for future migrations. Do not edit manually – it will be overwritten
// when new migrations are added.
// -----------------------------------------------------------------------------

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OracleDemo.Data;

#nullable disable

namespace OracleDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307110735_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OracleDemo.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_DATE");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("PRICE");

                    b.Property<string>("ProductName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PRODUCT_NAME");

                    b.HasKey("ProductId");

                    b.ToTable("PRODUCTS");
                });
#pragma warning restore 612, 618
        }
    }
}
