// -----------------------------------------------------------------------------
// 1.0 – Initial Migration – Creates the PRODUCTS table (before indexing)
// -----------------------------------------------------------------------------
// This migration was auto-generated by EF Core when the project was first created.
// It creates the PRODUCTS table with columns: PRODUCT_ID, PRODUCT_NAME, PRICE, CREATED_DATE.
// At this stage, NO indexes were added to the table.
// This serves as the "before" state for our indexing performance comparison.
// -----------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OracleDemo.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PRODUCTS",
                columns: table => new
                {
                    PRODUCT_ID = table.Column<int>(type: "NUMBER(10)", nullable: false)
                        .Annotation("Oracle:Identity", "START WITH 1 INCREMENT BY 1"),
                    PRODUCT_NAME = table.Column<string>(type: "NVARCHAR2(2000)", nullable: true),
                    PRICE = table.Column<decimal>(type: "DECIMAL(18, 2)", nullable: false),
                    CREATED_DATE = table.Column<DateTime>(type: "TIMESTAMP(7)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PRODUCTS", x => x.PRODUCT_ID);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PRODUCTS");
        }
    }
}
